### ISSUE TITLE
Project Page Previous and Next Arrows

### ISSUE THREAD

**Issue by DavidMGurr** [zacharyrnewton/David-Gurr#3]
When inside a project, such as "Fulton", I really like the addition of the "Next" and "Previous" arrows on the top left and right. Could we just remove the type and leave only the arrows? I feel that there is just too much type competing with each other. I personally think that the user would be able to navigate without the text, thoughts?

**Comment by zacharyrnewton** [comment]
Okay, no problem @DavidMGurr I can remove the text for you; I think it will still be clear enough without it.
