### ISSUE TITLE
Information Page Remove "David Gurr"

### ISSUE THREAD

**Issue by DavidMGurr** [zacharyrnewton/David-Gurr#4]
Please remove the "David Gurr" header above my description paragraph, it is too visually repetitive since my name is at the top anyways.

**Comment by zacharyrnewton** [comment]
Ok

**Comment by zacharyrnewton** [comment]
@DavidMGurr Do you want anything else there or do you just want to completely remove the header?

**Comment by DavidMGurr** [comment]
Let's change it to "About".
