### ISSUE TITLE
Images Not Showing Up (The Coffee Standard)

### ISSUE THREAD

**Issue by DavidMGurr** [zacharyrnewton/David-Gurr#8]
Hey Zach,

Can you take a look at The Coffee Standard project draft? When I preview it, I am not seeing all the images. It is my first time attempting to use GIFs as well.

Thanks

**Comment by DavidMGurr** [comment]
Seems to be working now, weird!

**Comment by zacharyrnewton** [comment]
No problem lol. I am curious to know why that didn't work at first. Let me know if it happens again. Glad the GIFs are working for you now. Looking forward to seeing them on the site. @DavidMGurr
